[package]
name = "eloquentlog-backend-api"
version = "0.0.1"
authors = ["Yasuhiro Яша Asaka <yasuhiro.asaka@grauwoelfchen.net>"]
description = "A backend api server for Eloquentlog."
repository = "https://gitlab.com/eloquentlog/eloquentlog-backend-api"
keywords = []
license = "AGPL-3.0-or-later"

[[test]]
name = "integration"
path = "test/test.rs"

[dependencies]
accord = { git = "https://github.com/ChrisBuchholz/accord.git", rev = "e56cecc" }
bcrypt = "0.3"
chrono = { version = "0.4.6", features = ["serde"] }
diesel = { version = "1.4.2", features = ["chrono", "postgres", "r2d2"] }
dotenv = "0.10"
lazy_static = "1.0"
parking_lot = "0.7.1"
regex = "0.2"
rocket = "0.4.0"
rocket_codegen = "*"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
uuid = { version = "0.7", features = ["serde", "v4"] }

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]
