[package]
name = "montafon"
version = "0.1.0"
authors = ["Yasuhiro Asaka <yasuhiro.asaka@grauwoelfchen.net>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["handlebars_templates"]
