[package]
autobins = false
name = "eloquentlog-backend-api"
version = "0.0.1"
authors = ["Yasuhiro Яша Asaka <yasuhiro.asaka@grauwoelfchen.net>"]
description = "A backend api server for Eloquentlog."
repository = "https://gitlab.com/eloquentlog/eloquentlog-backend-api"
keywords = []
license = "AGPL-3.0-or-later"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "worker"
path = "src/bin/worker.rs"

[[test]]
name = "integration"
path = "test/test.rs"

[dependencies]
accord = { git = "https://github.com/ChrisBuchholz/accord.git", rev = "e56cecc" }
bcrypt = "0.3"
chrono = { version = "0.4.6", features = ["serde"] }
dotenv = "0.10"
jsonwebtoken = "5.0"
lazy_static = "1.0"
oppgave = { git = "https://github.com/badboy/oppgave.git", rev = "3128dc6" }
parking_lot = "0.7.1"
redis = "0.9.0"
regex = "0.2"
rocket = "0.4.1"
rocket_codegen = "*"
rocket-slog = "0.4"
rusty-fork = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
slog = "2.4"
sloggers = "0.3"
uuid = "0.7"

[dependencies.diesel]
version = "1.4.2"
default-features = false
features = ["chrono", "postgres", "r2d2", "uuidv07"]

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]
