[package]
name = "eloquentlog-backend-api"
version = "0.0.1"
authors = ["Yasuhiro Яша Asaka <yasuhiro.asaka@grauwoelfchen.net>"]
description = "A backend api server for Eloquentlog."
repository = "https://gitlab.com/eloquentlog/eloquentlog-backend-api"
keywords = []
license = "AGPL-3.0-or-later"

[dependencies]
regex = "0.2"
rocket = "0.4.0"
rocket_codegen = "*"
diesel = { version = "1.0", features = ["postgres"] }
r2d2-diesel = "1.0"
r2d2 = "0.8"
dotenv = "0.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
lazy_static = "1.0"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]
