# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
import_types = [
  "diesel::sql_types::*",
  "eloquentlog_backend_api::model::message::LogLevel",
  "eloquentlog_backend_api::model::message::LogFormat",
  "eloquentlog_backend_api::model::user::EUserActivationState",
]
